### ISSUE TITLE
crash running update on "jack"

### ISSUE THREAD

**Issue by mucbuc** [mucbuc/crimp#13]
```
pull test/lib/objectify
{ [Error: stdout maxBuffer exceeded.]
  cmd: '/bin/sh -c git subtree pull -P test/lib/objectify test/lib/objectify master --squash' }
/usr/local/lib/node_modules/m_/bin/pull_subtree.js:18
        throw error;
        ^

Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:244:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by mucbuc** [comment]
m_ not jack
